version-template: '$MAJOR.$MINOR.$PATCH'
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  ## What’s Changed

  $CHANGES
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
  - title: '🧪 Tests'
    label: 'test'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
autolabeler:
  - label: 'chore'
    branch:
      - '/chore\/.+/'
  - label: 'doc'
    branch:
      - '/doc\/.+/'
      - '/documentation\/.+/'
  - label: 'test'
    branch:
      - '/test\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/feat\/.+/'
      - '/feature\/.+/'
    title:
      - '/feat/i'
      - '/feature/i'