name: Code linting
on: ["push"]
jobs:
  lint:
    name: Code linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Run Codacy Analysis
        uses: codacy/codacy-analysis-cli-action@master
